version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      GIPHY_AUTH_TOKEN: r9tTc0B4mBp7CPtOAgmKDBBTsDvzl5mV
    volumes:
      - ./backend:/myapp/backend
  frontend:
    container_name: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    command: "yarn dev"
    depends_on:
      - backend
  yaichi:
    container_name: yaichi
    image: mtsmfm/yaichi:1.5.0
    ports:
      - 80:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
